name: Auto-tag

on:
  push:
    branches:
      - master

env:
  PIPENV_NOSPIN: "true"
  ASGARD_VER: "0.1.1"
  GIT_USER_NAME: Claude-bot
  GIT_USER_EMAIL: github-actions-asgard@nerdin.space

jobs:
  auto-release:
    name: Auto-tag
    runs-on: ubuntu-18.04
    container:
      image: python:3.7.4-slim-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Test and auto-tag
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            ca-certificates \
            curl \
            build-essential \
            git \
            openssh-client
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"
          pip install pipenv
          pipenv sync --dev
          pipenv run inv check build test

          curl -sSLo /usr/local/bin/asgard --retry 10 \
          https://github.com/claudeleveille/asgard/releases/download/v$ASGARD_VER/asgard-$(uname -s)-$(uname -m)
          chmod +x /usr/local/bin/asgard
          asgard --version

          for i in {1..10}; do
            asgard --tag
            if [ "$?" = "0" ]; then
              break
            else
              sleep 1
              git fetch origin
              git reset --hard origin/$GITHUB_REF
            fi
          done

          git push --tags
