name: Auto-release

on:
  push:
    branches:
      - master

env:
  ASGARD_VER: "0.1.0"
  GIT_USER_NAME: Claude-bot
  GIT_USER_EMAIL: github-actions-asgard@nerdin.space

jobs:
  auto-release:
    name: Auto-release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build Binary
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            git \
            openssh-client
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"
          pip install pipenv
          pipenv sync --dev
          pipenv run inv check build test

      - name: Auto-release
        run: |
          curl -sSLo /usr/local/bin/asgard --retry 10 \
          https://github.com/claudeleveille/asgard/releases/download/v$ASGARD_VER/asgard-$(uname -s)-$(uname -m)
          chmod +x /usr/local/bin/asgard
          asgard --version

          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"

          for i in {1..10}; do
            asgard --tag
            if [ "$?" = "0" ]; then
              break
            else
              sleep 1
              git fetch origin
              git reset --hard origin/$GITHUB_REF
            fi
          done

          git push --tags
