name: Build

on:
  - pull_request

env:
  PIPENV_NOSPIN: "true"
  GIT_USER_NAME: Claude-bot
  GIT_USER_EMAIL: github-actions-asgard@nerdin.space

jobs:
  build-linux-x86_64:
    name: Build Linux x86_64 Binary
    runs-on: ubuntu-18.04
    container:
      image: python:3.7.5
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build Binary
        run: |
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"

          pip install pipenv
          pipenv sync --dev
          pipenv run inv check build test

  build-linux-x86_64-merge-result:
    name: Build Linux x86_64 Binary (Merge Result)
    runs-on: ubuntu-18.04
    container:
      image: python:3.7.5
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build Binary
        run: |
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"

          git fetch origin
          git checkout origin/master
          git merge $GITHUB_REF

          pip install pipenv
          pipenv sync --dev
          pipenv run inv check build test
