name: Build

on:
  - pull_request

env:
  PIPENV_NOSPIN: "true"

jobs:
  build-linux-x86_64:
    name: Build Linux x86_64 Binary
    runs-on: ubuntu-18.04
    container:
      image: python:3.7.5
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build Binary
        run: |
          git config --global user.name ci
          git config --global user.email ci
          pip install pipenv
          make
